# Generated by Django 3.2.6 on 2021-08-16 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constant_data', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='city_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constant_data.city'),
        ),
    ]
