# Generated by Django 3.2.6 on 2021-09-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_address_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
