# Generated by Django 3.2.6 on 2021-12-05 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constant_data', '0003_supplementaryinsurance'),
        ('patients', '0006_patient_last_used_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='has_social_security_insurance',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='supplementary_insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constant_data.supplementaryinsurance'),
        ),
    ]
