# Generated by Django 3.2.6 on 2021-11-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_last_used_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
