# Generated by Django 3.2.6 on 2021-12-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_patient_national_id'),
        ('patients', '0007_auto_20211205_1259'),
    ]

    operations = [
    ]
