# Generated by Django 3.2.6 on 2022-02-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_auto_20220129_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='has_social_security_insurance',
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance',
            field=models.CharField(choices=[('tamin', 'tamin'), ('salamat', 'salamat'), ('mosalah', 'mosalah'), ('other', 'other'), ('none', 'none')], default='none', max_length=20),
        ),
    ]
