# Generated by Django 3.2.6 on 2021-08-24 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constant_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constant_data.city'),
        ),
    ]
