# Generated by Django 3.2.6 on 2021-12-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constant_data', '0002_alter_city_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementaryInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('fa_name', models.CharField(max_length=32)),
            ],
        ),
    ]
